name: Build and Publish to NPM

on:
  push:
    branches:
      - master

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Update version
        run: |
          npm version patch --no-git-tag-version
          echo "Updated version in package.json"

      - name: Build
        run: npm run build

      - name: Pack the lib
        run: npm pack

      - name: Authenticate with npm registry
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc

      - name: Publish to NPM
        run: npm publish

      - name: Create and push git tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a v$(node -p "require('./package.json').version") -m "Release v$(node -p "require('./package.json').version")"
          git push origin --tags

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
